insert into locations (Name, Details, [Status]) values('Aula 1','Aula 1',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario Aula 1','Servicio Sanitario Aula 1',1)
insert into locations (Name, Details, [Status]) values('Aula impresión','Aula impresión',1)
insert into locations (Name, Details, [Status]) values('Aula 2','Aula 2',1)
insert into locations (Name, Details, [Status]) values('Aula 3','Aula 3',1)
insert into locations (Name, Details, [Status]) values('Aula 4','Aula 4',1)
insert into locations (Name, Details, [Status]) values('Aula 5','Aula 5',1)
insert into locations (Name, Details, [Status]) values('Aula 6','Aula 6',1)
insert into locations (Name, Details, [Status]) values('Aula 7','Aula 7',1)
insert into locations (Name, Details, [Status]) values('Aula 8','Aula 8',1)
insert into locations (Name, Details, [Status]) values('Aula 9','Aula 9',1)
insert into locations (Name, Details, [Status]) values('Aula 10','Aula 10',1)
insert into locations (Name, Details, [Status]) values('Sala de Profesores','Sala de Profesores',1)
insert into locations (Name, Details, [Status]) values('Odontologia','Odontologia',1)
insert into locations (Name, Details, [Status]) values('Recepcion','Recepcion',1)
insert into locations (Name, Details, [Status]) values('Aula 14','Aula 14',1)
insert into locations (Name, Details, [Status]) values('Educación abierta','Educación abierta',1)
insert into locations (Name, Details, [Status]) values('Biblioteca','Biblioteca',1)
insert into locations (Name, Details, [Status]) values('Secretaria de Direccion','Secretaria de Direccion',1)
insert into locations (Name, Details, [Status]) values('Cuarto de Redes','Cuarto de Redes',1)
insert into locations (Name, Details, [Status]) values('Asistente de Direccion','Asistente de Direccion',1)
insert into locations (Name, Details, [Status]) values('Direccion','Direccion',1)
insert into locations (Name, Details, [Status]) values('Aula PIAD','Aula PIAD',1)
insert into locations (Name, Details, [Status]) values('Sala de espera Direccion','Sala de espera Direccion',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario Hombres 1 nivel','Servicio Sanitario Hombres 1 nivel',1)
insert into locations (Name, Details, [Status]) values('Aula 11','Aula 11',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario de Personal Hombres 1er piso','Servicio Sanitario de Personal Hombres 1er piso',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario Mujeres 1 er piso','Servicio Sanitario Mujeres 1 er piso',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario Discapacitados 1 er piso','Servicio Sanitario Discapacitados 1 er piso',1)
insert into locations (Name, Details, [Status]) values('Pasillo Servicio Sanitario Mujeres 1er piso','Pasillo Servicio Sanitario Mujeres 1er piso',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario de Personal Mujeres 1 er piso','Servicio Sanitario de Personal Mujeres 1 er piso',1)
insert into locations (Name, Details, [Status]) values('Aula 12','Aula 12',1)
insert into locations (Name, Details, [Status]) values('Aula 13','Aula 13',1)
insert into locations (Name, Details, [Status]) values('Aula 15','Aula 15',1)
insert into locations (Name, Details, [Status]) values('Aula 16','Aula 16',1)
insert into locations (Name, Details, [Status]) values('Aula 17','Aula 17',1)
insert into locations (Name, Details, [Status]) values('Aula 21','Aula 21',1)
insert into locations (Name, Details, [Status]) values('Aula 18','Aula 18',1)
insert into locations (Name, Details, [Status]) values('Aula 19','Aula 19',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario hombres 2do piso','Servicio Sanitario hombres 2do piso',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario de personal de hombres 2do piso','Servicio Sanitario de personal de hombres 2do piso',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario mujeres 2 do piso ','Servicio Sanitario mujeres 2 do piso ',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario de personal mujeres 2 do piso ','Servicio Sanitario de personal mujeres 2 do piso ',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario discapacitados 2 do piso','Servicio Sanitario discapacitados 2 do piso',1)
insert into locations (Name, Details, [Status]) values('Pasillo Servicio Sanitario Mujeres 2do piso','Pasillo Servicio Sanitario Mujeres 2do piso',1)
insert into locations (Name, Details, [Status]) values('Aula 23','Aula 23',1)
insert into locations (Name, Details, [Status]) values('Aula 22','Aula 22',1)
insert into locations (Name, Details, [Status]) values('Aula 24','Aula 24',1)
insert into locations (Name, Details, [Status]) values('Aula 25','Aula 25',1)
insert into locations (Name, Details, [Status]) values('Aula 26','Aula 26',1)
insert into locations (Name, Details, [Status]) values('Aula 27','Aula 27',1)
insert into locations (Name, Details, [Status]) values('Aula 28','Aula 28',1)
insert into locations (Name, Details, [Status]) values('Pasillo Servicio Sanitario hombres 2do piso','Pasillo Servicio Sanitario hombres 2do piso',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario mujeres 2 do piso','Servicio Sanitario mujeres 2 do piso',1)
insert into locations (Name, Details, [Status]) values('Pasillo Servicio Sanitario mujeres 2do piso ','Pasillo Servicio Sanitario mujeres 2do piso ',1)
insert into locations (Name, Details, [Status]) values('Aula 29','Aula 29',1)
insert into locations (Name, Details, [Status]) values('Aula 30','Aula 30',1)
insert into locations (Name, Details, [Status]) values('Aula 31','Aula 31',1)
insert into locations (Name, Details, [Status]) values('Aula 32','Aula 32',1)
insert into locations (Name, Details, [Status]) values('Aula 33','Aula 33',1)
insert into locations (Name, Details, [Status]) values('Aula 34','Aula 34',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 34','Frente Aula 34',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 33','Frente Aula 33',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 29','Frente Aula 29',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 31','Frente Aula 31',1)
insert into locations (Name, Details, [Status]) values('Frente Servicio Sanitario 2do piso','Frente Servicio Sanitario 2do piso',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 28','Frente Aula 28',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 26','Frente Aula 26',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 25','Frente Aula 25',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 21','Frente Aula 21',1)
insert into locations (Name, Details, [Status]) values('Frente Biblioteca','Frente Biblioteca',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 19','Frente Aula 19',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 18','Frente Aula 18',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 01','Frente Aula 01',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 02','Frente Aula 02',1)
insert into locations (Name, Details, [Status]) values('Cubiculo modulo1','Cubiculo modulo1',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 05','Frente Aula 05',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 08','Frente Aula 08',1)
insert into locations (Name, Details, [Status]) values('Sala Profesores','Sala Profesores',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 11','Frente Aula 11',1)
insert into locations (Name, Details, [Status]) values('Sanitario 1 er piso ','Sanitario 1 er piso ',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 13','Frente Aula 13',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 15','Frente Aula 15',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 16','Frente Aula 16',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 17','Frente Aula 17',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 22','Frente Aula 22',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 23','Frente Aula 23',1)
insert into locations (Name, Details, [Status]) values('Frente Servicio Sanitario Hombres 2° piso','Frente Servicio Sanitario Hombres 2° piso',1)
insert into locations (Name, Details, [Status]) values('Frente a Servicio Sanitario Mujeres 2° piso','Frente a Servicio Sanitario Mujeres 2° piso',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 30','Frente Aula 30',1)
insert into locations (Name, Details, [Status]) values('Frente Aula 1','Frente Aula 1',1)
insert into locations (Name, Details, [Status]) values('Frente Modulo1','Frente Modulo1',1)
insert into locations (Name, Details, [Status]) values('Frente Area administrativa','Frente Area administrativa',1)
insert into locations (Name, Details, [Status]) values('Frente Recepción','Frente Recepción',1)
insert into locations (Name, Details, [Status]) values('Frente Servicio Sanitario Mujeres 1° piso','Frente Servicio Sanitario Mujeres 1° piso',1)
insert into locations (Name, Details, [Status]) values('Frente Comedor','Frente Comedor',1)
insert into locations (Name, Details, [Status]) values('Costado Norte Comedor','Costado Norte Comedor',1)
insert into locations (Name, Details, [Status]) values('Frente a Informatica','Frente a Informatica',1)
insert into locations (Name, Details, [Status]) values('Frente Gimnasio','Frente Gimnasio',1)
insert into locations (Name, Details, [Status]) values('Entrada principal','Entrada principal',1)
insert into locations (Name, Details, [Status]) values('Bodega','Bodega',1)
insert into locations (Name, Details, [Status]) values('Estrada Oeste Gimnasio','Estrada Oeste Gimnasio',1)
insert into locations (Name, Details, [Status]) values('Entrada Este adentro Gimnasio','Entrada Este adentro Gimnasio',1)
insert into locations (Name, Details, [Status]) values('Entrada Este Gimnasio','Entrada Este Gimnasio',1)
insert into locations (Name, Details, [Status]) values('Detrás modulo 2','Detrás modulo 2',1)
insert into locations (Name, Details, [Status]) values('Detrás Sala Profesores','Detrás Sala Profesores',1)
insert into locations (Name, Details, [Status]) values('Costado Oeste de edificio','Costado Oeste de edificio',1)
insert into locations (Name, Details, [Status]) values('Sala espera dirección','Sala espera dirección',1)
insert into locations (Name, Details, [Status]) values('Cuarto redes','Cuarto redes',1)
insert into locations (Name, Details, [Status]) values('Aula Física','Aula Física',1)
insert into locations (Name, Details, [Status]) values('Oficina Física','Oficina Física',1)
insert into locations (Name, Details, [Status]) values('Cuarto electrico Gimnasio','Cuarto electrico Gimnasio',1)
insert into locations (Name, Details, [Status]) values('Gimnasio','Gimnasio',1)
insert into locations (Name, Details, [Status]) values('Comedor','Comedor',1)
insert into locations (Name, Details, [Status]) values('Bodega salon de actos','Bodega salon de actos',1)
insert into locations (Name, Details, [Status]) values('Pasillo 2º piso gradas emergencias','Pasillo 2º piso gradas emergencias',1)
insert into locations (Name, Details, [Status]) values('Sala espera modulo 2','Sala espera modulo 2',1)
insert into locations (Name, Details, [Status]) values('Pasillo 1º piso gradas emergencias','Pasillo 1º piso gradas emergencias',1)
insert into locations (Name, Details, [Status]) values('Sala espera modulo 1','Sala espera modulo 1',1)
insert into locations (Name, Details, [Status]) values('Dirección','Dirección',1)
insert into locations (Name, Details, [Status]) values('Servicio Sanitario Dirección','Servicio Sanitario Dirección',1)
insert into locations (Name, Details, [Status]) values('Pasillo 2º piso   ','Pasillo 2º piso   ',1)
insert into locations (Name, Details, [Status]) values('Pasillo 2º piso','Pasillo 2º piso',1)
insert into locations (Name, Details, [Status]) values('Pasillo 1º piso ','Pasillo 1º piso ',1)
insert into locations (Name, Details, [Status]) values('Gradas emergencias','Gradas emergencias',1)
insert into locations (Name, Details, [Status]) values('Pasillo de la rampa','Pasillo de la rampa',1)
insert into locations (Name, Details, [Status]) values('Bodega de conserje 1° piso','Bodega de conserje 1° piso',1)
insert into locations (Name, Details, [Status]) values('Bodega de conserje 2° piso','Bodega de conserje 2° piso',1)
insert into locations (Name, Details, [Status]) values('Debajo de las gradas','Debajo de las gradas',1)
insert into locations (Name, Details, [Status]) values('Boveda','Boveda',1)
insert into locations (Name, Details, [Status]) values('Bodega limpienza','Bodega limpienza',1)
insert into locations (Name, Details, [Status]) values('Pasillo Servicio Sanitario de hombres','Pasillo Servicio Sanitario de hombres',1)
